### ISSUE TITLE
Plugin doesn't completely work

### ISSUE THREAD

**Issue by mazzy89** [senecajs/seneca-joi#2]
I'm trying to use this plugin but it doesn't work:

```javascript
import 'babel-polyfill'

import Config from 'getconfig'
import Seneca from 'seneca'
import Search from './srv/search'

const {
  seneca,
  isolated,
  fixer
} = Config

const Service = Seneca(seneca)

Service
  .use('joi')
  .use(Search, fixer)
  .listen(isolated)
```

when I start the application, it falls back give a generic error:

```
2016-06-06T17:18:16.816Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search INFO	hello	Seneca/2.1.0/5vu1zfjq7i0e/1465233496798/94313/currency-converter-search
2016-06-06T17:18:16.818Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	options	{ tag: 'currency-converter-search',   legacy: { validate: false, error_codes: true },   log: { map: [ { level: 'all', handler: 'print' } ] },   idlen: 12,   timeout: 11111,   default_plugins:     { basic: true,      cluster: true,      'mem-store': true,      repl: true,      transport: true,      web: true },   debug:     { fragile: false,      undead: false,      print: { options: false },      act_caller: false,      short_logs: false,      callpoint: false },   strict:     { result: true,      fixedargs: true,      add: false,      find: true,      maxloop: 11 },   actcache: { active: true, size: 11111 },   trace: { act: false, stack: false, unknown: 'warn' },   stats: { size: 1024, interval: 60000, running: false },   deathdelay: 11111,   admin: { local: false, prefix: '/admin' },   plugin: {},   internal:     { close_signals: { SIGHUP: true, SIGTERM: true, SIGINT: true, SIGBREAK: true },      catchall: false,      actrouter: ,      subrouter:  },   status: { interval: 60000, running: false },   zig: {},   pin: { immediate: false } }
2016-06-06T17:18:16.830Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(aowssasdtcjp)	cmd:stats,role:seneca	action_seneca_stats
2016-06-06T17:18:16.831Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(c1zptcgbwixw)	cmd:close,role:seneca	action_seneca_close
2016-06-06T17:18:16.831Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(5rqijfsfho1r)	info:fatal,role:seneca	action_seneca_fatal
2016-06-06T17:18:16.832Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(hzscbq9d71r4)	get:options,role:seneca	action_options_get
2016-06-06T17:18:16.832Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(kp1mnpoti6ea)	role:seneca,stats:true	action_seneca_stats
2016-06-06T17:18:16.833Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(lo1rpdqdi426)	cmd:get,role:options	action_options_get
2016-06-06T17:18:16.919Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(c5wwumoe0pkb)	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin_definition
2016-06-06T17:18:16.946Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(olkf7afyw9r8)	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin_definition
2016-06-06T17:18:16.998Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(vsscmk3umvkw)	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin_definition
2016-06-06T17:18:17.074Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(b4w428j58dku)	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin_definition
2016-06-06T17:18:17.080Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search FATAL	sys	seneca	2.1.0	5vu1zfjq7i0e/1465233496798/94313/currency-converter-search	plugin_not_found	seneca: use-plugin: Could not load plugin joi; require search list: joi, seneca-joi, ./joi, ./seneca-joi.	{}	-
2016-06-06T17:18:17.086Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	ADD	(8j9p2c1sgfzp)	name:seneca-y6o42d,plugin:define,role:seneca,seq:5,tag:undefined	plugin_definition
2016-06-06T17:18:17.087Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search INFO	listen	{host:localhost,port:40001}
2016-06-06T17:18:17.095Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	IN	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	{role:seneca,plugin:define,name:basic,tag:null,seq:1}	ENTRY	(c5wwumoe0pkb)	-	-	GATE
2016-06-06T17:18:17.097Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	register	init	basic		{}
2016-06-06T17:18:17.098Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(daggaug2z5xl)	cmd:quickcode,role:basic	quickcode
2016-06-06T17:18:17.099Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(vf0fdkjdirn7)	cmd:generate_id,role:basic	generate_id
2016-06-06T17:18:17.100Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(egvpb4w8kce4)	cmd:quickcode,role:util	quickcode
2016-06-06T17:18:17.100Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(3pyrrjpq6l9n)	cmd:generate_id,role:util	generate_id
2016-06-06T17:18:17.101Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(dhg9ulm4p2fj)	cmd:ensure_entity,role:basic	ensure_entity
2016-06-06T17:18:17.101Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(n0fpjls75htm)	cmd:define_sys_entity,role:basic	define_sys_entity
2016-06-06T17:18:17.102Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(3qig0jebhnx4)	cmd:ensure_entity,role:util	ensure_entity
2016-06-06T17:18:17.102Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(b6srafr6f068)	cmd:define_sys_entity,role:util	define_sys_entity
2016-06-06T17:18:17.102Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(69cabwn9on4z)	cmd:set,note:true,role:basic	set
2016-06-06T17:18:17.103Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(k1ormxe7tsnv)	cmd:get,note:true,role:basic	get
2016-06-06T17:18:17.104Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(gzci2mirhop6)	cmd:list,note:true,role:basic	list
2016-06-06T17:18:17.104Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(a7e0m38s2qch)	cmd:push,note:true,role:basic	push
2016-06-06T17:18:17.104Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(cd6jd301q2le)	cmd:pop,note:true,role:basic	pop
2016-06-06T17:18:17.105Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(aearq0xcs22r)	cmd:set,note:true,role:util	set
2016-06-06T17:18:17.106Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(bytlc1ycdz6u)	cmd:get,note:true,role:util	get
2016-06-06T17:18:17.109Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(vm3x5xi4tf4f)	cmd:list,note:true,role:util	list
2016-06-06T17:18:17.109Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(y18rshtd5bfn)	cmd:push,note:true,role:util	push
2016-06-06T17:18:17.110Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	ADD	(vmsu9fekjy7f)	cmd:pop,note:true,role:util	pop
2016-06-06T17:18:17.110Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	plugin	basic       	options	set	{basic:{}}
2016-06-06T17:18:17.115Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	register	install	basic	{exports:[basic]}
2016-06-06T17:18:17.115Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	act	-	-	DEFAULT	{init:basic,tag:null}
2016-06-06T17:18:17.117Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	-       	OUT	74krgx7hikgr/cjadnknfin5t		{}	EXIT		-	-	1-
2016-06-06T17:18:17.117Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	register	ready	basic	{}
2016-06-06T17:18:17.118Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	OUT	pgz7c4r37r3j/cjadnknfin5t	name:basic,plugin:define,role:seneca,seq:1,tag:undefined	null	EXIT	(c5wwumoe0pkb)	-	-	197	GATE
2016-06-06T17:18:17.118Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	IN	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	{role:seneca,plugin:define,name:seneca-uvhuqw,tag:null,seq:2}	ENTRY	(olkf7afyw9r8)	-	-	GATE
2016-06-06T17:18:17.119Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	register	init	seneca-uvhuqw		{}
2016-06-06T17:18:17.120Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(4rife587rimq)	cmd:save,role:entity
2016-06-06T17:18:17.120Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(h1dlychtue6h)	cmd:load,role:entity
2016-06-06T17:18:17.121Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(fj4iq5jy8imm)	cmd:list,role:entity
2016-06-06T17:18:17.121Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(kfi9og5ess0n)	cmd:remove,role:entity
2016-06-06T17:18:17.122Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(p44jmyic6083)	cmd:close,role:seneca
2016-06-06T17:18:17.122Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(fenpe2fma1fx)	cmd:native,role:entity
2016-06-06T17:18:17.123Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(25a66m4xi6bq)	cmd:dump,role:mem-store
2016-06-06T17:18:17.124Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(bs8c97x4wj9w)	cmd:export,role:mem-store
2016-06-06T17:18:17.124Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(oel3djle1z9w)	cmd:import,role:mem-store
2016-06-06T17:18:17.124Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	ADD	(cfxpr33uc9wt)	init:mem-store
2016-06-06T17:18:17.124Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	plugin	seneca-uvhuqw	options	set	{"seneca-uvhuqw":{}}
2016-06-06T17:18:17.127Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	register	install	mem-store/1	{exports:[mem-store/1/native]}	seneca-uvhuqw
2016-06-06T17:18:17.128Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	mem-store/1	IN	32h4g74fxzoq/f4qy3pm3vf37	init:mem-store	{init:mem-store,tag:1}	ENTRY	(cfxpr33uc9wt)	-	-	-
2016-06-06T17:18:17.128Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	mem-store/1	OUT	32h4g74fxzoq/f4qy3pm3vf37	init:mem-store	null	EXIT	(cfxpr33uc9wt)--	0	-
2016-06-06T17:18:17.129Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	register	ready	mem-store$1
2016-06-06T17:18:17.129Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	OUT	l64znyf2ca9w/f4qy3pm3vf37	name:seneca-uvhuqw,plugin:define,role:seneca,seq:2,tag:undefined	null	EXIT	(olkf7afyw9r8)	-	-	183	GATE
2016-06-06T17:18:17.129Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	IN	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	{role:seneca,plugin:define,name:transport,tag:null,seq:3}	ENTRY	(vsscmk3umvkw)	-	-	GATE
2016-06-06T17:18:17.129Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	register	init	transport		{}
2016-06-06T17:18:17.132Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(djxb1kwq75u8)	cmd:inflight,role:transport
2016-06-06T17:18:17.133Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(xmh63evrb71z)	cmd:listen,role:transport
2016-06-06T17:18:17.133Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(t7uxim4mgs77)	cmd:client,role:transport
2016-06-06T17:18:17.133Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(6sbm43hqrjie)	hook:listen,role:transport,type:tcp
2016-06-06T17:18:17.134Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(68de8dommzbf)	hook:client,role:transport,type:tcp
2016-06-06T17:18:17.134Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(pkf34okhx7dl)	hook:listen,role:transport,type:web
2016-06-06T17:18:17.135Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(ezgxktx5kp60)	hook:client,role:transport,type:web
2016-06-06T17:18:17.135Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(e97sn9y2fs24)	hook:listen,role:transport,type:http
2016-06-06T17:18:17.135Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(lwr4zfw2vgb3)	hook:client,role:transport,type:http
2016-06-06T17:18:17.135Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(hzuebn1utup2)	hook:listen,role:transport,type:direct
2016-06-06T17:18:17.136Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ADD	(pzf7jv5skoc0)	hook:client,role:transport,type:direct
2016-06-06T17:18:17.136Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	options	set	{transport:{msgprefix:seneca_,callmax:111111,msgidlen:12,warn:{unknown_message_id:true,invalid_kind:true,invali
2016-06-06T17:18:17.139Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	register	install	transport	{exports:[transport/utils]}
2016-06-06T17:18:17.139Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	act	-	-	DEFAULT	{init:transport,tag:null}
2016-06-06T17:18:17.139Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	-       	OUT	htggfnffkkzo/sp6xq43lorht		{}	EXIT		-	-	0-
2016-06-06T17:18:17.139Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	register	ready	transport	{}
2016-06-06T17:18:17.139Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	OUT	yon8ag92xp4q/sp6xq43lorht	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	null	EXIT	(vsscmk3umvkw)	-	-	141	GATE
2016-06-06T17:18:17.140Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	IN	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	{role:seneca,plugin:define,name:seneca-ee4sy0,tag:null,seq:4}	ENTRY	(b4w428j58dku)	-	-	GATE
2016-06-06T17:18:17.140Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	register	init	seneca-ee4sy0		{}
2016-06-06T17:18:17.152Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(ojpyvru4wnva)	role:web	web_use
2016-06-06T17:18:17.152Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(skaktr5gadaj)	list:service,role:web	list_service
2016-06-06T17:18:17.153Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(0qpvll6hu6lv)	list:route,role:web	list_route
2016-06-06T17:18:17.153Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(teeiuytcso0e)	role:web,stats:true	action_stats
2016-06-06T17:18:17.154Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(nkn2qo4ww865)	get:config,role:web	get_config
2016-06-06T17:18:17.154Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(5vioas2k296n)	role:web,set:source	set_source
2016-06-06T17:18:17.155Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(edvujr2opeq7)	get:sourcelist,role:web	get_sourcelist
2016-06-06T17:18:17.155Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(ajtjvnqmnynq)	do:startware,role:web	default_startware
2016-06-06T17:18:17.155Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(11x9pou6fh1s)	get:server,role:web	get_server
2016-06-06T17:18:17.156Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(muw8rejchrrn)	get:restriction,role:web	default_get_restriction
2016-06-06T17:18:17.156Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(ykeqnsetjeyb)	role:web,set:framework	set_framework
2016-06-06T17:18:17.157Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(cko9vns9bgp4)	handle:response,role:web	handle_response
2016-06-06T17:18:17.158Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	ADD	(mpzwexrc6xkq)	init:web
2016-06-06T17:18:17.158Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	plugin	seneca-ee4sy0	options	set	{"seneca-ee4sy0":{}}
2016-06-06T17:18:17.160Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	register	install	web	{exports:[web,web/httprouter,web/hapi]}	seneca-ee4sy0
2016-06-06T17:18:17.160Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	web       	IN	4gvcs6rfqxn2/jy01mcisu6gg	init:web	{init:web,tag:null}	ENTRY	(mpzwexrc6xkq)	-	-	-
2016-06-06T17:18:17.161Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	web       	OUT	4gvcs6rfqxn2/jy01mcisu6gg	init:web	null	EXIT	(mpzwexrc6xkq)--	1	-
2016-06-06T17:18:17.161Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	-	-	ACT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	register	ready	web
2016-06-06T17:18:17.161Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	root$       	OUT	witlvoto5tnu/jy01mcisu6gg	name:seneca-ee4sy0,plugin:define,role:seneca,seq:4,tag:undefined	null	EXIT	(b4w428j58dku)	-	-	87	GATE
2016-06-06T17:18:17.162Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	web       	IN	9u4kcylyn9am/jy01mcisu6gg	role:web	{role:web,plugin:web,config:{prefix:/seneca}}	ENTRY	(ojpyvru4wnva)	-	-	-
2016-06-06T17:18:17.162Z 5vu1zfjq7i0e/1465233496798/94313/currency-converter-search DEBUG	act	web       	OUT	9u4kcylyn9am/jy01mcisu6gg	role:web	null	EXIT	(ojpyvru4wnva)--	1	-

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/mazzy/.nvm/versions/node/v6.2.0/bin/node" "/Users/mazzy/.nvm/versions/node/v6.2.0/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! currency-converter-search@1.0.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the currency-converter-search@1.0.0 start script 'node dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the currency-converter-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs currency-converter-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls currency-converter-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/npm-debug.log
```

**Comment by mazzy89** [comment]
I've also tried this config:

```javascript
import 'babel-polyfill'

import Config from 'getconfig'
import Seneca from 'seneca'
import Search from './srv/search'

const {
  isolated,
  fixer
} = Config

const Service = Seneca({
  legacy: {validate: false} // needed if using Seneca 2.x
})

Service
  .use('joi')
  .use(Search, fixer)
  .listen(isolated)
```

and the error is the following:

```
> currency-converter-search@1.0.0 start /Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search
> node dist/index.js

2016-06-06T19:29:45.591Z 0acmdycdu4vp/1465241385573/97940/- INFO	hello	Seneca/2.1.0/0acmdycdu4vp/1465241385573/97940/-
2016-06-06T19:29:45.851Z 0acmdycdu4vp/1465241385573/97940/- FATAL	sys	seneca	2.1.0	0acmdycdu4vp/1465241385573/97940/-	plugin_not_found	seneca: use-plugin: Could not load plugin joi; require search list: joi, seneca-joi, ./joi, ./seneca-joi.	{}	-
2016-06-06T19:29:45.860Z 0acmdycdu4vp/1465241385573/97940/- INFO	listen	{host:localhost,port:40001}


Seneca Fatal Error
==================

Message: seneca: use-plugin: Could not load plugin joi; require search list: joi, seneca-joi, ./joi, ./seneca-joi.

Code: plugin_not_found

Details: { 'orig$':
   { Error: use-plugin: Could not load plugin joi; require search list: joi, seneca-joi, ./joi, ./seneca-joi.
       at errormaker (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/eraro/eraro.js:94:15)
       at Object.use (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/use-plugin/use.js:94:13)
       at Seneca.api_use [as use] (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca/seneca.js:997:29)
       at Object.<anonymous> (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/dist/index.js:28:9)
       at Module._compile (module.js:541:32)
       at Object.Module._extensions..js (module.js:550:10)
       at Module.load (module.js:458:32)
```

**Comment by mazzy89** [comment]
I've tried this config and the error is also different:

```javascript
import 'babel-polyfill'

import Config from 'getconfig'
import Seneca from 'seneca'
import Search from './srv/search'

const {
  isolated,
  fixer
} = Config

const Service = Seneca({
  legacy: {validate: false} // needed if using Seneca 2.x
})

Service
  .use(require('seneca-joi'))
  .use(Search, fixer)
  .listen(isolated)
```

```
> currency-converter-search@1.0.0 start /Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search
> node dist/index.js

2016-06-06T19:31:34.370Z zvzidyvjuwzd/1465241494352/98106/- INFO	hello	Seneca/2.1.0/zvzidyvjuwzd/1465241494352/98106/-
2016-06-06T19:31:34.683Z zvzidyvjuwzd/1465241494352/98106/- INFO	listen	{host:localhost,port:40001}
2016-06-06T19:31:34.749Z zvzidyvjuwzd/1465241494352/98106/- ERROR	act	web       	OUT		role:web	6	{role:web,plugin:web,config:{prefix:/seneca}}	ENTRY	(o4jp6icnkykv)-seneca: Action role:web has invalid arguments; child "use" fails because ["use" must be an object]; arguments were: { role: 'web',
  plugin: 'web',
  config: { prefix: '/seneca' },
  use: [Function] }.	act_invalid_args	{pattern:role:web,message:child "use" fails because ["use" must be an object],msg:{role:web,plugin:web,config:{	Error: seneca: Action role:web has invalid arguments; child "use" fails because ["use" must be an object]; arguments were: { role: 'web',
  plugin: 'web',
  config: { prefix: '/seneca' },
  use: [Function] }.
    at Object.errormaker [as error] (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/eraro/eraro.js:94:15)
    at /Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca/seneca.js:1513:19
    at internals.Any._validateWithOptions (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca-joi/node_modules/joi/lib/any.js:664:16)
    at root.validate (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca-joi/node_modules/joi/lib/index.js:103:23)
    at Object.joi_validate [as validate] (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca-joi/joi.js:26:17)
    at validate_action_message (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca/seneca.js:1507:18)
    at Object.execute_action [as fn] (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/seneca/seneca.js:1115:7)
    at Immediate._onImmediate (/Users/mazzy/vagrant-devbox/currency-converter/currency-converter-search/node_modules/gate-executor/gate-executor.js:136:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by otaviosoares** [comment]
I have the same issue.

**Comment by arthurvi** [comment]
Same here, any progress on this?

**Comment by rjrodger** [comment]
@mazzy89 @arthurvi @otaviosoares I can't reproduce directly.
I have tightened up the testing so seneca-joi is verified against seneca 2.1.0
This plugin will be the default in Seneca 3.0, out soon /cc @mcdonnelldean

Could you provide a self-contained example of the bug via github gist? - thanks

**Comment by arthurvi** [comment]
@rjrodger Thanks for your response. I created a gist here: https://gist.github.com/arthurvi/ae2d05d3c28cce8171b12dd6ab6d071f
It is actually a very basic setup. I don't think it has anything to do with the node version huh? I'm running v6.3.1.

**Comment by rjrodger** [comment]
This codes works for me on both node 4.4.4 and 6.3.0. I saved both files to a new folder, and then ran the commands:

```sh
$ npm install
$ node server.js
```

with output:

```txt
2016-08-02T13:26:40.780Z lbkdii6w3b14/1470144400706/25817/- INFO	hello	Seneca/2.1.0/lbkdii6w3b14/1470144400706/25817/-	
2016-08-02T13:26:42.074Z lbkdii6w3b14/1470144400706/25817/- INFO	listen	{type:tcp}
```

Could you verify that your node_modules folder contains the correct versions, as here:

```sh
$ npm list --depth=0
seneca-joi-test@1.0.0 /home/ubuntu/Projects/aaa
├── seneca@2.1.0
├── seneca-entity@1.0.0
└── seneca-joi@0.2.0
```

In the folder containing these files, what happens when you run

```sh
$ node -e 'require("seneca-joi")'
```
(it should succeed with no output and no errors)

**Comment by arthurvi** [comment]
Whoops, I forgot to add the most important part in the gist... Sorry!
I updated it now. 
```
// Initialize seneca and start listening
seneca
	.use('entity');
```
Should have been
```
// Initialize seneca and start listening
seneca
	.use('entity')
	.use('joi');
```

```node -e 'require("seneca-joi")'``` Does work for me btw, no logging or whatsoever. 

Also everything in node_modules is correct
```
npm list --depth=0
seneca-joi-test@1.0.0 /Users/arthurvisser/dev/tst
├── seneca@2.1.0
├── seneca-entity@1.0.0
└── seneca-joi@0.2.0
```

**Comment by rjrodger** [comment]
OK! Should be fixed on 0.3.0!
The plugin was trying to interpret old parambulator validation rules. I did not trigger this case in the previous unit tests (and that's why 100% coverage does not mean what you think it means!).

**Comment by mazzy89** [comment]
Unfortunately no luck. I've still the same error. Here my example project https://github.com/mazzy89/currency-converter-search/tree/develop which can be easily run. Please let me know if I'm missing something there because I've tried and strictly followed your examples but nothing.

**Comment by arthurvi** [comment]
Unfortunately it doesn't work for me neither. The gist still gives the same error after I updated to 0.3.0. Anything I can do to help? It seems to be some issue with the naming or something?
```
seneca-joi-test@1.0.0 /Users/arthurvisser/dev/tst
├── joi@9.0.4
├── seneca@2.1.0
├── seneca-entity@1.2.0
└── seneca-joi@0.3.0
```

**Comment by rjrodger** [comment]
Thanks guys - yes, the parambulator check was missing a few cases - sorry - please try 0.3.1

**Comment by mazzy89** [comment]
@rjrodger still nothing. always the same error

**Comment by arthurvi** [comment]
@mazzy89 @rjrodger Same error here as well.

**Comment by rjrodger** [comment]
@arthurvi more investigation! could you clone this repo - seneca-joi - and let me know if `npm test` works for you?

@mazzy89 I cloned your project on the develop branch. You're doing some manipulation of the modules that seems to be breaking the plugin loading - by using `require` directly, it seems to solve the problem:

```js
Service
  .use(require('seneca-entity'))
  .use(require('seneca-joi'))
  .use(Search(deps), fixer)
  .listen(isolated)
```

**Comment by mazzy89** [comment]
@rjrodger yes in that way it works like a charm ;-)

**Comment by arthurvi** [comment]
npm test works fine!

```
> seneca-joi@0.3.1 test /Users/arthurvisser/dev/seneca-joi
> lab -v -P test -L -t 90 -I Reflect

joi
  ✔ 1) happy (549 ms)
  ✔ 2) custom (91 ms)
  ✔ 3) edge (79 ms)
  ✔ 4) defensives (0 ms)
  ✔ 5) parambulator-legacy (96 ms)
  ✔ 6) is_parambulator (1 ms)


6 tests complete
Test duration: 823 ms
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
```

When I do the require stuff it now seems to work ok! Before this gave errors too.
```
seneca
	.use(require('seneca-entity'))
	.use(require('seneca-joi'));
```

So almost there I guess!

**Comment by rjrodger** [comment]
@arthurvi ok so we can exclude your node environment. Does the require thing fully resolve the issue?

**Comment by arthurvi** [comment]
@rjrodger Yes! Before when I tried `require('seneca-joi')` this gave errors too. Now the server just starts! I'm now building a test that actually uses Joi as validation. 
I'm not really familiar with how seneca does the `seneca-` prefixing stuff. Is it something with an incorrect name in the package.json?

**Comment by rjrodger** [comment]
It's just a convenience abbreviation. It will break if you pass a seneca object around into other modules, so best bet is to just use require in all cases if your architecture is like that.

**Comment by arthurvi** [comment]
@rjrodger Thank you for your help. Tested it with an actual Joi implementation and it works. Should we document that `require('seneca-joi')` is required? Because as seen in my gist using just `.use('joi')` already breaks at the most basic implementation right?
